# Generated by Django 5.1.7 on 2025-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_no', models.CharField(max_length=10)),
                ('discount_percentage', models.IntegerField()),
                ('min_order_price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
