# Generated by Django 5.1.7 on 2025-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='if_active',
            field=models.BooleanField(default=False),
        ),
    ]
