# Generated by Django 5.1.7 on 2025-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_if_active_categories_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kilogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
