# Generated by Django 5.1.7 on 2025-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_variant_delete_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_quantitiy',
            field=models.IntegerField(default=0),
        ),
    ]
