# Generated by Django 5.1.7 on 2025-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_variant_quantitiy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
