# Generated by Django 5.1.7 on 2025-07-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_offer',
            name='category',
        ),
    ]
