# Generated by Django 5.1.7 on 2025-07-18 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_category_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('backup_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
    ]
