# Generated by Django 5.1.7 on 2025-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_offers',
            name='backup_price',
        ),
        migrations.AddField(
            model_name='category_offers',
            name='backup_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
