# Generated by Django 5.1.7 on 2025-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_is_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
