# Generated by Django 5.1.7 on 2025-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_wallet_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_history',
            name='order_id',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
