# Generated by Django 5.1.7 on 2025-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_wallet_history_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_history',
            name='order_id',
            field=models.IntegerField(default=0, max_length=25),
        ),
    ]
