# Generated by Django 5.1.7 on 2025-08-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_wallet_history_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet_history',
        ),
    ]
