# Generated by Django 5.1.7 on 2025-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_wallet_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_history',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
