# Generated by Django 5.1.7 on 2025-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_wallet_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet_history',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
