# Generated by Django 5.1.7 on 2025-08-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_wallet_history_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_history',
            name='order_id',
        ),
    ]
