# Generated by Django 5.1.7 on 2025-08-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_wallet_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wallet_history',
        ),
    ]
