# Generated by Django 5.1.7 on 2025-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='return_image/'),
        ),
    ]
