# Generated by Django 5.1.7 on 2025-06-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_if_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='if_active',
            new_name='is_active',
        ),
    ]
