# Generated by Django 5.1.7 on 2025-07-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_kilogram_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kilogram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
