# Generated by Django 5.1.7 on 2025-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='variants',
        ),
    ]
