# Generated by Django 5.1.7 on 2025-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_variant_id_product_variant_quantitiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_quantitiy',
        ),
        migrations.AddField(
            model_name='product',
            name='variant_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
