# Generated by Django 5.1.7 on 2025-07-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_category_offer_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_offer',
        ),
    ]
